apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: configserver
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: configserver
    # set this if needing configserver to only be resolvable on cluster
    # networking.knative.dev/visibility: cluster-local
  annotations:
    autoscaling.knative.dev/minScale: "0"
spec:
  source:
    image: dev.local:5000/configserver:latest
  env:
    - name: "org.springframework.cloud.bindings.boot.enable"
      value: "true"
  build:
    env:
      - name: BP_NATIVE_IMAGE
        value: "true"
      - name: BP_JVM_VERSION
        value: "17.*"
